content:
  - name: projects
    label: Video Projects
    path: src/content/projects
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: vimeoId
        label: Vimeo ID
        type: string
        required: true
        description: "Just the ID, not the full URL (e.g., '76979871')"
      - name: thumbnail
        label: Thumbnail URL
        type: string
        description: "Optional. If not provided, will use Vimeo thumbnail"
      - name: category
        label: Category
        type: select
        required: true
        options:
          values:
            - Commercial
            - Music Video
            - Documentary
            - Short Film
            - Corporate
      - name: client
        label: Client
        type: string
      - name: date
        label: Date
        type: date
        required: true
      - name: featured
        label: Featured Project
        type: boolean
        default: false
      - name: body
        label: Project Details
        type: rich-text
        description: "Add project overview, credits, technical details, etc."

media:
  input: public/images
  output: /images
